POST http://localhost:8080/login
Content-Type: application/json

{
	"username": "user",
	"password": "password"
}
###
DELETE http://localhost:8080/users?id=fha7ltt1irh
Authorization: 8kzrid3qpso

###
GET http://localhost:8080/users?id=someId
Authorization: 8kzrid3qpso

###
GET http://localhost:8080/users?name=John
Authorization: 8kzrid3qpso

###
PUT http://localhost:8080/users
Authorization: 8kzrid3qpso
Content-Type: application/json

{
	"age": 30,
	"email": "some@email.com",
	"name": "SomeName",
	"workingPosition": 3
}